### ISSUE TITLE
直接git clone会生成BJT-Template目录，不能直接Template目录

### ISSUE THREAD

**Issue by fengtion11** [SmallK111407/BJT-Template#1]
不知道有没有影响
我是用以下方法，直接Template目录

> 
cd /你的yunzai目录/Yunzai-Bot/plugins/xiaoyao-cvs-plugin/resources/dailyNote/
git init
git remote add origin  https://gitee.com/SmallK111407/BJT-Template.git
git config core.sparsecheckout true
echo "Template" >> .git/info/sparse-checkout
git pull origin master
>

**Comment by SmallK111407** [comment]
该库提供的使用方法就是用库内Template文件夹与图鉴插件内Template文件夹合并,目前(2022/8/18)我并没有做完该背景图合集,最好是在我做完之后再进行合并。
